apiVersion: v2
appVersion: "2.10.0"
version: 2.10.0
description: A Helm chart for elastic operator (wrapped)
name: eck-operator
dependencies:
- name: eck-operator
  version: 2.10.0
  repository: file://./eck-operator
